[package]
name = "bluetooth"
version = "0.1.0"
edition = "2021"

[lib]
name="bluetooth"
crate-type=["cdylib"]

[dependencies]
btleplug = "0.9.2"
napi = { version = "2", features=["async"] }
napi-derive = "2"

[build-dependencies]
napi-build = "1"