[package]
name = "bluetooth"
version = "0.1.0"
edition = "2021"

[lib]
name="bluetooth"
crate-type=["cdylib"]

[dependencies]
btleplug = "0.9.2"
node-bindgen = { version = "4.0" }

[build-dependencies]
node-bindgen = { version = "4.0", features = ["build"] }